### PR TITLE
apt.kubernetes.io has been replaced by pkgs.k8s.io

### PR DESCRIPTION
**Pull request by pmcgleenon**
Thanks for making this available, it's very useful!   I needed to make a few tweaks to get it working:

- Updated the kubernetes repositories since [apt.kubernetes.io has been deprecated](https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation)

- Also added non-interactive configuration for `needrestart`, otherwise it asks for confirmation when installing kubeadm

### CODE REVIEW

**Comment by pmcgleenon** [comment]
hi @jimangel  here's a PR to get this working with the latest kubernetes version

**Comment by jimangel** [comment]
Hey @pmcgleenon! Apologies for missing this in October, thank you so much for updating this!

Let me test it out on my side and I'll merge it once it works. 🚀

**Comment by pmcgleenon** [comment]
Thanks, there are some deprecation warnings which could be cleaned up
I just pushed an update for `1.32.0`

**Review by jimangel — APPROVED** [review]
lgtm! Thanks again!

**Pull request merged**
